/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.awt.Color;
import java.awt.Graphics;
/**
 *
 * @author hi-tech
 */
public class Display extends java.awt.Frame {

    /**
     * Creates new form Display
     */
    Connection con;
    PreparedStatement stmt;
    ResultSet rs;
    public Display() {
        initComponents();
        setSize(400,510);
        try{
       Class.forName("org.gjt.mm.mysql.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/school","root","");
         for(int i=1;i<=10;i++){ ch1.add(i+"");  }
       }catch(Exception ee){System.out.println("eror:"+ee);}
            
        
     }
    int a=0;
    int b=0;
    int c=0;
    int angle=90;
    public void paint(Graphics gg)
    {  System.out.println("a="+a);
       System.out.println("a="+b);
       System.out.println("a="+c);
       System.out.println("a="+angle);
        gg.setColor(new Color(a,b,c));
    
      gg.fillArc(5,375,150,150,0,angle);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ts = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        label9 = new java.awt.Label();
        label7 = new java.awt.Label();
        textField11 = new java.awt.TextField();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        canvas3 = new java.awt.Canvas();
        label12 = new java.awt.Label();
        label4 = new java.awt.Label();
        textField4 = new java.awt.TextField();
        textField15 = new java.awt.TextField();
        textField16 = new java.awt.TextField();
        textField14 = new java.awt.TextField();
        textField13 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        tm = new java.awt.Label();
        t1 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        Maths = new java.awt.Label();
        label6 = new java.awt.Label();
        label8 = new java.awt.Label();
        button1 = new java.awt.Button();
        label10 = new java.awt.Label();
        status = new java.awt.Label();
        t4 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        t7 = new java.awt.TextField();
        t8 = new java.awt.TextField();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        total = new java.awt.Label();
        label15 = new java.awt.Label();
        t9 = new java.awt.TextField();
        label16 = new java.awt.Label();
        button2 = new java.awt.Button();
        ch1 = new java.awt.Choice();

        ts.setText("textField1");

        textField5.setText("textField1");

        textField1.setText("textField1");

        textField2.setText("textField1");

        textField6.setText("textField1");

        textField3.setText("textField1");

        jFormattedTextField1.setText("jFormattedTextField1");

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setText("Marks");

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText("Hindi");

        textField11.setText("textField11");

        canvas2.setName("can1"); // NOI18N

        label12.setText("label12");

        label4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        label4.setText("Subject Teacher");

        textField4.setText("textField4");

        textField15.setText("textField4");

        textField16.setText("textField4");

        textField14.setText("textField4");

        textField13.setText("textField4");

        t3.setName("t3"); // NOI18N

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Class");
        add(label1);
        label1.setBounds(20, 100, 60, 23);

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("RolI no");
        add(label2);
        label2.setBounds(20, 40, 60, 23);

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Name");
        add(label3);
        label3.setBounds(20, 70, 60, 23);

        tm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tm.setText("Science");
        add(tm);
        tm.setBounds(10, 170, 60, 23);

        t1.setName("t1"); // NOI18N
        add(t1);
        t1.setBounds(90, 40, 150, 20);

        t2.setName("t2"); // NOI18N
        add(t2);
        t2.setBounds(90, 70, 150, 20);

        Maths.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Maths.setText("Maths");
        add(Maths);
        Maths.setBounds(10, 200, 60, 23);

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setText("sst");
        add(label6);
        label6.setBounds(10, 230, 60, 23);

        label8.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        label8.setText("Marks");
        add(label8);
        label8.setBounds(20, 130, 60, 28);

        button1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button1.setLabel("Search");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(270, 60, 80, 40);

        label10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label10.setText("English");
        add(label10);
        label10.setBounds(10, 260, 60, 23);

        status.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        status.setName("status"); // NOI18N
        add(status);
        status.setBounds(260, 400, 100, 23);
        add(t4);
        t4.setBounds(80, 170, 90, 20);
        add(t5);
        t5.setBounds(80, 200, 90, 20);
        add(t6);
        t6.setBounds(80, 230, 90, 20);

        t7.setName("t7"); // NOI18N
        add(t7);
        t7.setBounds(80, 260, 90, 20);
        add(t8);
        t8.setBounds(80, 290, 90, 20);

        label13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label13.setText("Computer");
        add(label13);
        label13.setBounds(210, 170, 70, 23);

        label14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label14.setName("status"); // NOI18N
        label14.setText("status");
        add(label14);
        label14.setBounds(190, 400, 60, 20);

        total.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        total.setName("total"); // NOI18N
        add(total);
        total.setBounds(260, 355, 100, 28);

        label15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label15.setText("Total");
        add(label15);
        label15.setBounds(200, 360, 50, 20);
        add(t9);
        t9.setBounds(290, 170, 90, 20);

        label16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label16.setText("Hindi");
        add(label16);
        label16.setBounds(10, 290, 60, 20);

        button2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button2.setLabel("exit");
        button2.setName("b2"); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(210, 450, 80, 27);
        add(ch1);
        ch1.setBounds(90, 100, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        try{
        stmt=con.prepareStatement("select * from report where rollno=? ");
        stmt.setString(1,t1.getText());
       
        rs=stmt.executeQuery();
        while(rs.next())
        {
            String s2=rs.getString(2);
             String s3=rs.getString(3);
              String s4=rs.getString(4);
               String s5=rs.getString(5);
                String s6=rs.getString(6);
                 String s7=rs.getString(7);
                  String s8=rs.getString(8);
                  String s9=rs.getString(9);
                  //String s=s3+"";
                  String s =ch1.getSelectedItem();
                  System.out.println(s+s3);
                  if(s3.equals(ch1.getSelectedItem()))
                  {t2.setText(s2);
                  t4.setText(s4); t5.setText(s5);
                  t6.setText(s6); t7.setText(s7); t8.setText(s8); t9.setText(s9);
                  String s10=rs.getString(10);
                  int x=Integer.parseInt(s10);
                  total.setText(x+"/600");
                  if(x<180){status.setText("Fail"); }
                  else{status.setText("pass");}
                  angle=(int)((x/600.0)*360.0);
                  System.out.println("angle"+angle);
                  if(1<=x&&x<=180){a=255;b=0;c=0;}
                  else if(181<=x&&x<=350){c=255;a=0;b=0;}
                  else{b=255;a=0;c=0;}}
                  repaint();
        }
        }catch(Exception ee){System.out.println("error:"+ee);}
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Maths;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private java.awt.Canvas canvas3;
    private java.awt.Choice ch1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label status;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    private java.awt.TextField t9;
    private java.awt.TextField textField1;
    private java.awt.TextField textField11;
    private java.awt.TextField textField13;
    private java.awt.TextField textField14;
    private java.awt.TextField textField15;
    private java.awt.TextField textField16;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.Label tm;
    private java.awt.Label total;
    private java.awt.TextField ts;
    // End of variables declaration//GEN-END:variables
}
