/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hi-tech
 */
public class fees extends java.awt.Frame {

    /**
     * Creates new form fees
     */
    java.util.Date d1=new java.util.Date();
    int a1=d1.getDate();
    int a2=d1.getMonth()+1;
    int a3=d1.getYear()+1900;
    Connection con;
    PreparedStatement stmt;
    ResultSet rs;
    public fees() {
        initComponents();
        setSize(600,500);
         try{
       Class.forName("org.gjt.mm.mysql.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/school","root","");               
       }catch(Exception ee){System.out.println("eror:"+ee);}
          ch1.add(" ");
         ch1.add("jan+feb+march+examfee");
        ch1.add("april+may+june");
        ch1.add("july+aug+septmber");
        ch1.add("october+november+december+examfee");
        ch2.add(" ");
       for(int i=1;i<=10;i++){ ch2.add(i+"");  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        t5 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        t1 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        label9 = new java.awt.Label();
        ch1 = new java.awt.Choice();
        search = new java.awt.Button();
        label10 = new java.awt.Label();
        ch2 = new java.awt.Choice();

        label1.setText("label1");

        label3.setText("label1");

        label4.setText("label1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setLabel("exit");
        button1.setName("b2"); // NOI18N

        t5.setName("t5"); // NOI18N

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("Total");
        add(label2);
        label2.setBounds(70, 180, 60, 20);

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setName(""); // NOI18N
        label5.setText("Registration No");
        add(label5);
        label5.setBounds(20, 30, 110, 20);

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("Name");
        add(label6);
        label6.setBounds(70, 60, 60, 20);

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setName(""); // NOI18N
        label7.setText("Father'sName");
        add(label7);
        label7.setBounds(20, 90, 110, 20);

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setName(""); // NOI18N
        label8.setText("Class");
        add(label8);
        label8.setBounds(70, 120, 50, 20);

        tab1.setAutoCreateRowSorter(true);
        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reg no", "Name", "Fathername"
            }
        ));
        jScrollPane2.setViewportView(tab1);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 270, 510, 160);

        t1.setName("t1"); // NOI18N
        add(t1);
        t1.setBounds(140, 30, 190, 20);

        t2.setName("t2"); // NOI18N
        add(t2);
        t2.setBounds(140, 60, 190, 20);

        t3.setName("t3"); // NOI18N
        add(t3);
        t3.setBounds(140, 90, 190, 20);

        t4.setName("t4"); // NOI18N
        add(t4);
        t4.setBounds(140, 120, 190, 20);

        t6.setName("t6"); // NOI18N
        add(t6);
        t6.setBounds(140, 180, 190, 20);

        button2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button2.setLabel("Submit");
        button2.setName("b1"); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(350, 110, 100, 27);

        button3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button3.setLabel("exit");
        button3.setName("b2"); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(340, 150, 110, 24);

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setName(""); // NOI18N
        label9.setText(" feesof ");
        add(label9);
        label9.setBounds(70, 150, 60, 20);

        ch1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch1ItemStateChanged(evt);
            }
        });
        add(ch1);
        ch1.setBounds(140, 150, 190, 20);

        search.setLabel("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        add(search);
        search.setBounds(350, 30, 110, 24);

        label10.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 0, 0));
        label10.setText("LIST OF FEES DEFAULTER OF CLASS");
        add(label10);
        label10.setBounds(50, 230, 254, 23);

        ch2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch2ItemStateChanged(evt);
            }
        });
        add(ch2);
        ch2.setBounds(320, 230, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
        stmt=con.prepareStatement("select *from student where regno=?");
        stmt.setString(1,t1.getText());
        rs=stmt.executeQuery();
        if(rs.next())
        {
         String s1=rs.getString("name");
         t2.setText(s1);
         String s2=rs.getString("fathername");
         t3.setText(s2);
        int pre=rs.getInt(9);
         t4.setText(pre+"");
        }
        
        }catch(Exception ee){System.out.println("ee:"+ee);}
    }//GEN-LAST:event_searchActionPerformed

    private void ch1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch1ItemStateChanged
        // TODO add your handling code here:
            int cls=Integer.parseInt(t4.getText());
           // System.out.println(cls);
           int fee=0;
        try{
            stmt=con.prepareStatement("select fees from structure where class=?");
            stmt.setString(1, Integer.toString(cls));
            
            rs=stmt.executeQuery();
           // System.out.println(rs.next());
            if(rs.next()){ fee=rs.getInt("fees");
               System.out.println(fee);}
            
            String s=ch1.getSelectedItem();
            
            
           // System.out.println(ss[0]);
            if(s.length()>=21){
                 fee*=3;fee+=100;
            }
            else{
                fee*=3; 
                
            }
            String s1=Integer.toString(fee);
           t6.setText(s1);
            
        }catch(Exception ee){System.out.println("ee:"+ee);}
    }//GEN-LAST:event_ch1ItemStateChanged
    
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
         try{
        stmt=con.prepareStatement("update deposit set submit=?,dos=? where regno=?");
        stmt.setString(3,t1.getText());
       // stmt.setString(2,t2.getText());
      //  stmt.setString(3,t3.getText());
        //stmt.setString(4,t4.getText());
        stmt.setString(1,"done");
        stmt.setString(2,a3+"-"+a2+"-"+a1);
        stmt.executeUpdate();
        t1.setText(" ");t2.setText(" ");
        t3.setText(" ");t4.setText(" ");
        t6.setText(" ");
        JOptionPane.showMessageDialog(this,"Your fees is submitted");
         }catch(Exception ee){ System.out.println("error:"+ee); }
    }//GEN-LAST:event_button2ActionPerformed

    private void ch2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch2ItemStateChanged
        // TODO add your handling code here:
       
        
        try{
            stmt=con.prepareStatement("select regno,name,father,dos,submit from deposit where class=? ");
            stmt.setString(1,ch2.getSelectedItem());
          
           // String ss=ch2.getSelectedItem();
            //System.out.println(ss);
            rs=stmt.executeQuery();
           // boolean b=rs.next();
            //System.out.println(b);
            //System.out.println("aa");
            String s5;
            while(rs.next())
            {  
                try{
                s5=rs.getString("submit");
                System.out.println(s5);
                if(s5.isEmpty())
                {throw new NullPointerException();}
                }catch(NullPointerException ee){
               
                  
                String s1=Integer.toString(rs.getInt("regno"));
                String s2=rs.getString("name");
                String s3=rs.getString("father");
                //String s4=rs.getString("dos");
                DefaultTableModel dtm=(DefaultTableModel)tab1.getModel();
                String[] arr={s1,s2,s3};
                dtm.addRow(arr);
          }
            }
            
        }catch(Exception ee){System.out.println("ee:"+ee);}
    }//GEN-LAST:event_ch2ItemStateChanged

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
    int a=JOptionPane.showConfirmDialog(this,"are you sure");
    if(a==0)   
    {dispose();}        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Choice ch1;
    private java.awt.Choice ch2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Button search;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private javax.swing.JTable tab1;
    // End of variables declaration//GEN-END:variables
}
