/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author hi-tech
 */
public class formc extends java.awt.Frame {

    /**
     * Creates new form formc
     */
    Connection con;
    PreparedStatement stmt;
    ResultSet  rs;
    int reg;
    public formc() {
        initComponents();
        setSize(500,600);
        ch1.add("UP");
        ch1.add("Punjab");
        ch1.add("Uttrathand");
        ch1.add("Harayana");
        try{
       Class.forName("org.gjt.mm.mysql.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/school","root","");
        /* stmt=con.prepareStatement("select * from student where class=?");
         //t8.getText();
        int x=Integer.parseInt(t8.getText())+1;
          String s1=Integer.toString(x);
         stmt.setString(1,s1);
         rs=stmt.executeQuery();
         boolean b=rs.next();
         System.out.println(b);
         while(rs.next())
         {
             reg=rs.getInt("regno");
         } */   
                 
       }catch(Exception ee){System.out.println("eror:1"+ee);}     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField13 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        textField1 = new java.awt.TextField();
        textField14 = new java.awt.TextField();
        label12 = new java.awt.Label();
        fees1 = new fees();
        t53 = new java.awt.TextField();
        t52 = new java.awt.TextField();
        ch2 = new java.awt.Choice();
        label3 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label1 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label13 = new java.awt.Label();
        t1 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        t3 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        ch1 = new java.awt.Choice();
        label2 = new java.awt.Label();
        t7 = new java.awt.TextField();
        t8 = new java.awt.TextField();
        lp = new java.awt.Label();
        ld = new java.awt.Label();
        Standard = new java.awt.Label();

        textField13.setText("textField1");
        textField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField13ActionPerformed(evt);
            }
        });

        textField4.setText("textField1");

        textField6.setText("textField1");

        textField1.setText("textField1");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        textField14.setText("textField1");
        textField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField14ActionPerformed(evt);
            }
        });

        label12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label12.setName("l6"); // NOI18N
        label12.setText("Previous Qualification");

        t53.setText("textField1");
        t53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t53ActionPerformed(evt);
            }
        });

        t52.setText("textField1");

        label3.setText("label3");

        label14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label14.setName("l6"); // NOI18N
        label14.setText("Previous Qualification");

        label15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label15.setName("l6"); // NOI18N
        label15.setText("Previous Qualification");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setName("l2"); // NOI18N
        label1.setText("Age:");
        add(label1);
        label1.setBounds(60, 100, 50, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setName("l1"); // NOI18N
        label4.setText("Name:");
        add(label4);
        label4.setBounds(60, 70, 50, 20);

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setName("l3"); // NOI18N
        label6.setText("Father's name");
        add(label6);
        label6.setBounds(20, 130, 103, 20);

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setName("l4"); // NOI18N
        label7.setText("mother's name");
        add(label7);
        label7.setBounds(20, 160, 110, 20);

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setName("l5"); // NOI18N
        label8.setText(" Date of Birth *");
        add(label8);
        label8.setBounds(30, 190, 100, 20);

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setName("l6"); // NOI18N
        label9.setText("Address:");
        add(label9);
        label9.setBounds(50, 220, 66, 20);

        label10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label10.setName("l6"); // NOI18N
        label10.setText("City");
        add(label10);
        label10.setBounds(30, 250, 30, 20);

        label11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label11.setName("l6"); // NOI18N
        label11.setText("State");
        add(label11);
        label11.setBounds(200, 250, 40, 20);

        label13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label13.setName("l6"); // NOI18N
        label13.setText("Previous Qualification *");
        add(label13);
        label13.setBounds(10, 280, 170, 20);

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        add(t1);
        t1.setBounds(130, 70, 210, 20);

        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
        });
        add(t4);
        t4.setBounds(140, 160, 220, 20);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t6KeyPressed(evt);
            }
        });
        add(t6);
        t6.setBounds(140, 220, 200, 20);

        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        add(t3);
        t3.setBounds(130, 130, 200, 20);

        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        add(t2);
        t2.setBounds(130, 100, 200, 20);

        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t5MouseEntered(evt);
            }
        });
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
        });
        add(t5);
        t5.setBounds(140, 190, 190, 20);

        button1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 255, 0));
        button1.setLabel("Save");
        button1.setName("b1"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(30, 320, 90, 32);

        button2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button2.setForeground(new java.awt.Color(153, 0, 0));
        button2.setLabel("Cancel");
        button2.setName("b2"); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(190, 320, 120, 30);

        ch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ch1KeyPressed(evt);
            }
        });
        add(ch1);
        ch1.setBounds(250, 250, 130, 20);

        label2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setText("ADDMISSION FORM");
        add(label2);
        label2.setBounds(60, 30, 230, 30);

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t7KeyPressed(evt);
            }
        });
        add(t7);
        t7.setBounds(70, 250, 120, 20);

        t8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t8MouseEntered(evt);
            }
        });
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        t8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t8KeyPressed(evt);
            }
        });
        add(t8);
        t8.setBounds(190, 280, 30, 20);

        lp.setName("lp"); // NOI18N
        lp.setText("*- if no previous qualification then type null ");
        lp.setVisible(false);
        add(lp);
        lp.setBounds(10, 410, 310, 30);

        ld.setName("ld"); // NOI18N
        ld.setText("* - Date should be formetted like -(year-month-date)");
        ld.setVisible(false);
        add(ld);
        ld.setBounds(10, 380, 310, 30);

        Standard.setText("Standard");
        add(Standard);
        Standard.setBounds(230, 280, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void t53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t53ActionPerformed

    private void textField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField13ActionPerformed

    private void textField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField14ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        try{
            stmt=con.prepareStatement("select * from student where class=?");
            String s1=t8.getText();
            int x=Integer.parseInt(s1)+1;
                s1=Integer.toString(x);
         stmt.setString(1,s1);
         rs=stmt.executeQuery();
         //boolean b=rs.next();
        // System.out.println(b);
         int Max=0;
         while(rs.next())
         {
             reg=rs.getInt("regno");
             System.out.println(reg);
             if(reg>Max){Max=reg;}
         } reg=Max;
            }catch(Exception ee){System.out.println("ee="+ee);}
      
        reg=reg+1;
           
        try{ 
            //reg=reg+1;
           // System.out.println(reg);
            String s= Integer.toString(reg);
           stmt=con.prepareStatement("Insert into student values(?,?,?,?,?,?,?,?,?,?)");
           stmt.setString(1,s);
           stmt.setString(2,t1.getText());
           stmt.setString(3,t2.getText());
           stmt.setString(4,t3.getText());
           stmt.setString(5,t4.getText());
           stmt.setString(10,t5.getText());
           stmt.setString(6,t6.getText());
           stmt.setString(7,t7.getText());
           stmt.setString(8,ch1.getSelectedItem());
           int x=Integer.parseInt(t8.getText())+1;
           stmt.setString(9,Integer.toString(x));
          stmt.executeUpdate();
          
        }catch(Exception ee){System.out.println("error="+ee);}
         int fak=reg;
         
        try{ int r=0;
            System.out.println(fak);
        if(fak>=101&&fak<200){ r=fak-100;    }
            else if(201<=fak&&fak<300){r=fak-200;}
            else  if(301<=fak&&fak<400){ r=fak-300;  }
            else if(401<=fak&&fak<500){r=fak-400;  }
            else if(501<=fak&fak<600){r=fak-500;}
            else  if(601<=fak&&fak<700){ r=fak-600;  }
            else if(701<=fak&&fak<800){r=fak-700;  }
             else if(801<=fak&&fak<900){r=fak-800;}
            else  if(901<=fak&&fak<1000){ r=fak-900;  }
            else {if(1001<=fak&&fak<1100){r=fak-1000;  }}
          stmt=con.prepareStatement("Insert into report(rollno,name,class) values(?,?,?)");
          String q=t8.getText();
          String n="null";
          String p="preschool";
          if(q.equals(n)){stmt.setString(3,"preschool");}
          else{
              int a=(Integer.parseInt(q)+1);
               p=Integer.toString(a);
               //System.out.println(r);
             stmt.setString(1,Integer.toString(r));
             stmt.setString(2,t1.getText());
              stmt.setString(3,p);
              }
           stmt.executeUpdate();
           try{
               stmt=con.prepareStatement("insert into deposit(regno,name,father,class) values(?,?,?,?) ");
              stmt.setString(1,Integer.toString(reg));
              stmt.setString(2,t1.getText());
              stmt.setString(3,t3.getText());
              stmt.setString(4, p);
             stmt.executeUpdate();
              
           }catch(Exception ee){System.out.println("error:"+ee);}
           t1.setText("");
           t2.setText("");
           t3.setText("");
           t4.setText("");
           t5.setText("");
           t6.setText("");
           t7.setText("");
           t8.setText("");
      JOptionPane.showMessageDialog(this,"your Registration number="+reg+"\n"+"you are promoted to="+p+"th");
          }catch(Exception ee){System.out.println("error="+ee); }

    }//GEN-LAST:event_button1ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t5ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseEntered
        // TODO add your handling code here:
        ld.setVisible(true);
        lp.setVisible(false);
    }//GEN-LAST:event_t5MouseEntered

    private void t8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t8MouseEntered
        // TODO add your handling code here:
        lp.setVisible(true);
        ld.setVisible(false);
    }//GEN-LAST:event_t8MouseEntered

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
        // TODO add your handling code here||
      int k=evt.getKeyCode();
        if(k!=8&&(k<48||k>57)&&k!=45){evt.consume();}
         int a=evt.getKeyCode();
        if(a==10){t6.requestFocus();}
    }//GEN-LAST:event_t5KeyPressed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        // TODO add your handling code here:
        int a=evt.getKeyCode();
        if(a==10){t2.requestFocus();}
    }//GEN-LAST:event_t1KeyPressed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t3.requestFocus();}
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t4.requestFocus();}
    }//GEN-LAST:event_t3KeyPressed

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t5.requestFocus();}
    }//GEN-LAST:event_t4KeyPressed

    private void t6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t7.requestFocus();}
    }//GEN-LAST:event_t6KeyPressed

    private void t7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){ch1.requestFocus();}
    }//GEN-LAST:event_t7KeyPressed

    private void ch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ch1KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t8.requestFocus();}
    }//GEN-LAST:event_ch1KeyPressed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyPressed
        // TODO add your handling code here:
        try{int a=evt.getKeyCode();
        if(a!=8&&48>a||a>57){evt.consume();}
        String s1=t8.getText();
      if(s1.equals(" ")){} else{int x=Integer.parseInt(s1);}
      // if(x==10){ JOptionPane.showMessageDialog(this,"Invalid Class"); }
       
        }catch(Exception ee){System.out.println("error2::"+ee);}
       /* if(a==10){
            try{
            stmt=con.prepareStatement("select * from student where class=?");
            String s1=t8.getText();
            int x=Integer.parseInt(s1)+1;
                s1=Integer.toString(x);
         stmt.setString(1,s1);
         rs=stmt.executeQuery();
         boolean b=rs.next();
         System.out.println(b);
         while(rs.next())
         {
             reg=rs.getInt("regno");
         }
            }catch(Exception ee){System.out.println("ee="+ee);}
        }*/
    }//GEN-LAST:event_t8KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formc().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Standard;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Choice ch1;
    private java.awt.Choice ch2;
    private fees fees1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label ld;
    private java.awt.Label lp;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t52;
    private java.awt.TextField t53;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    private java.awt.TextField textField1;
    private java.awt.TextField textField13;
    private java.awt.TextField textField14;
    private java.awt.TextField textField4;
    private java.awt.TextField textField6;
    // End of variables declaration//GEN-END:variables
}
