/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
/**
 *
 * @author hi-tech
 */
public class reportcard extends java.awt.Frame {

    /**
     * Creates new form reportcard
     */
    Connection con;
    PreparedStatement stmt;
    ResultSet rs;
    public reportcard() {
        initComponents();
        setSize(600,500);
        try{
            Class.forName("org.gjt.mm.mysql.Driver");
          con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/school","root","");
         ch1.add("1");
         ch1.add("2");
         ch1.add("3");
         ch1.add("4");
         ch1.add("5");
         ch1.add("6");
         ch1.add("7");
         ch1.add("8");
         ch1.add("9");
         ch1.add("10");
        }catch(Exception ee){System.out.println("error="+ee);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new java.awt.Button();
        label5 = new java.awt.Label();
        list1 = new java.awt.List();
        t6 = new java.awt.TextField();
        label1 = new java.awt.Label();
        t1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        t2 = new java.awt.TextField();
        label6 = new java.awt.Label();
        tc = new java.awt.TextField();
        ts = new java.awt.TextField();
        tm = new java.awt.TextField();
        tss = new java.awt.TextField();
        te = new java.awt.TextField();
        th = new java.awt.TextField();
        bexit = new java.awt.Button();
        bsave = new java.awt.Button();
        ch1 = new java.awt.Choice();
        ll1 = new java.awt.List();

        b1.setLabel("button1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        label5.setText("label5");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Report");
        add(label1);
        label1.setBounds(70, 30, 70, 28);

        t1.setName("t1"); // NOI18N
        add(t1);
        t1.setBounds(90, 70, 180, 20);

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("Rollno");
        add(label2);
        label2.setBounds(30, 70, 60, 23);

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setName(""); // NOI18N
        label3.setText("Science    Maths    SSt     English    Hindi     Computer");
        add(label3);
        label3.setBounds(10, 180, 380, 23);

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Name");
        add(label4);
        label4.setBounds(30, 100, 60, 20);
        add(t2);
        t2.setBounds(90, 100, 190, 20);

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("class");
        add(label6);
        label6.setBounds(30, 130, 50, 23);
        add(tc);
        tc.setBounds(320, 210, 50, 20);

        ts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tsKeyPressed(evt);
            }
        });
        add(ts);
        ts.setBounds(10, 210, 50, 20);

        tm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tmKeyPressed(evt);
            }
        });
        add(tm);
        tm.setBounds(70, 210, 50, 20);

        tss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tssKeyPressed(evt);
            }
        });
        add(tss);
        tss.setBounds(130, 210, 50, 20);

        te.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teKeyPressed(evt);
            }
        });
        add(te);
        te.setBounds(190, 210, 50, 20);

        th.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                thKeyPressed(evt);
            }
        });
        add(th);
        th.setBounds(250, 210, 50, 20);

        bexit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bexit.setLabel("exit");
        bexit.setName("b2"); // NOI18N
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        add(bexit);
        bexit.setBounds(230, 260, 100, 30);

        bsave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bsave.setLabel("Save");
        bsave.setName("b1"); // NOI18N
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        add(bsave);
        bsave.setBounds(10, 260, 100, 27);

        ch1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch1ItemStateChanged(evt);
            }
        });
        add(ch1);
        ch1.setBounds(90, 130, 180, 20);

        ll1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ll1ItemStateChanged(evt);
            }
        });
        add(ll1);
        ll1.setBounds(400, 30, 80, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void ch1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch1ItemStateChanged
        // TODO add your handling code here:
        ll1.removeAll();
        try{
            stmt=con.prepareStatement("select name from report where class=?");
             String s=ch1.getSelectedItem();
             //System.out.println(s);
              
            stmt.setString(1,s);
           rs=stmt.executeQuery();
           while(rs.next())
           {   
               String s1=rs.getString("name");
               ll1.add(s1);
           }
        }catch(Exception ee){}
    }//GEN-LAST:event_ch1ItemStateChanged

    private void ll1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ll1ItemStateChanged
        // TODO add your handling code here:
        try{
            stmt=con.prepareStatement("select rollno,name from report where name=?");
            System.out.println(ll1.getSelectedItem());
            stmt.setString(1,ll1.getSelectedItem());
            rs=stmt.executeQuery();
            if(rs.next())
            {
               String s2=rs.getString("rollno");
               t1.setText(s2);
               String s3=ll1.getSelectedItem();
               t2.setText(s3);
            }    
        }catch(Exception ee){}
    }//GEN-LAST:event_ll1ItemStateChanged

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
         try{
             stmt=con.prepareStatement("Update report set science=?,maths=?,sst=?,English=?,hindi=?,computer=?,total=? where rollno=? and class=?");
                
                
               

             //stmt=con.prepareStatement("insert into report values(?,?,?,?,?,?,?,?,?,?)");
             stmt.setString(8,t1.getText());
             stmt.setString(9,ch1.getSelectedItem());
             //stmt.setString(2,t2.getText());
             //stmt.setString(3,ch1.getSelectedItem());
              String sa=ts.getText();
              System.out.println(sa);
             stmt.setString(1,ts.getText());
             stmt.setString(2,tm.getText());
             stmt.setString(3,tss.getText());
             stmt.setString(4,te.getText());
             stmt.setString(5,th.getText());
             stmt.setString(6,tc.getText());
             int s=Integer.parseInt(ts.getText());
             int m=Integer.parseInt(tm.getText());
             int ss=Integer.parseInt(tss.getText());
             int e=Integer.parseInt(te.getText());
             int h=Integer.parseInt(th.getText());
             int c=Integer.parseInt(tc.getText());
             int t=s+m+ss+e+h+c;
             System.out.println(t);
             stmt.setString(7,Integer.toString(t));
             stmt.executeUpdate();
            ts.setText(" "); te.setText(" ");
            tm.setText(" "); th.setText(" ");
            tss.setText(" "); tc.setText(" ");
            t1.setText(" "); t2.setText(" ");
         }catch(Exception ee){ System.out.println("error:"+ee); }
    }//GEN-LAST:event_bsaveActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bexitActionPerformed

    private void tsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsKeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){tm.requestFocus();}
    }//GEN-LAST:event_tsKeyPressed

    private void tmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmKeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){tss.requestFocus();}
    }//GEN-LAST:event_tmKeyPressed

    private void tssKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tssKeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){te.requestFocus();}
    }//GEN-LAST:event_tssKeyPressed

    private void teKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teKeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){th.requestFocus();}
    }//GEN-LAST:event_teKeyPressed

    private void thKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thKeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){tc.requestFocus();}
    }//GEN-LAST:event_thKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportcard().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button bexit;
    private java.awt.Button bsave;
    private java.awt.Choice ch1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.List list1;
    private java.awt.List ll1;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t6;
    private java.awt.TextField tc;
    private java.awt.TextField te;
    private java.awt.TextField th;
    private java.awt.TextField tm;
    private java.awt.TextField ts;
    private java.awt.TextField tss;
    // End of variables declaration//GEN-END:variables
}
