/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author hi-tech
 */
public class teacherrecruited extends java.awt.Frame {

    /**
     * Creates new form teacherrecruited
     */
    Connection con;
    PreparedStatement stmt;
    ResultSet rs;
    java.util.Date date=new java.util.Date();
    int a1=date.getDate();
    int a2=date.getMonth()+1;
    int a3=date.getYear()+1900;
   public teacherrecruited() {
        initComponents();
        setSize(600,500);
        try{
            Class.forName("org.gjt.mm.mysql.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/school","root","");
   
                         
        }catch(Exception ee){System.out.println("error"+ee);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label5 = new java.awt.Label();
        label4 = new java.awt.Label();
        label3 = new java.awt.Label();
        label2 = new java.awt.Label();
        label17 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        b2 = new java.awt.Button();
        b1 = new java.awt.Button();
        t3 = new java.awt.TextField();
        t4 = new java.awt.TextField();
        t5 = new java.awt.TextField();
        t6 = new java.awt.TextField();
        t1 = new java.awt.TextField();
        subj = new java.awt.TextField();
        t8 = new java.awt.TextField();
        t2 = new java.awt.TextField();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        t7 = new java.awt.TextField();

        label1.setText("label1");

        label5.setText("label5");

        label4.setText("label4");

        label3.setText("label3");

        label2.setText("label2");

        label17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label17.setName("l1"); // NOI18N
        label17.setText("Graduation");

        textField1.setText("textField1");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 0, 0));
        label7.setName("l1"); // NOI18N
        label7.setText("RecruitementForm");
        add(label7);
        label7.setBounds(90, 20, 210, 20);

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setName("l1"); // NOI18N
        label8.setText("Age");
        add(label8);
        label8.setBounds(40, 80, 50, 20);

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setName("l1"); // NOI18N
        label9.setText("Fathername");
        add(label9);
        label9.setBounds(20, 110, 90, 23);

        label10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label10.setName("l1"); // NOI18N
        label10.setText("Phone No");
        add(label10);
        label10.setBounds(30, 140, 80, 23);

        label11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label11.setName("l1"); // NOI18N
        label11.setText("Email ID");
        add(label11);
        label11.setBounds(30, 170, 59, 23);

        label12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label12.setName("l1"); // NOI18N
        label12.setText("City");
        add(label12);
        label12.setBounds(40, 230, 50, 23);

        label13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label13.setName("l1"); // NOI18N
        label13.setText("Address");
        add(label13);
        label13.setBounds(30, 200, 70, 23);

        label14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label14.setName("l1"); // NOI18N
        label14.setText("Subject");
        add(label14);
        label14.setBounds(20, 290, 90, 23);

        label15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label15.setName("l1"); // NOI18N
        label15.setText("years");
        add(label15);
        label15.setBounds(180, 260, 50, 20);

        b2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b2.setLabel("Cancel");
        b2.setName("b1"); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        add(b2);
        b2.setBounds(280, 330, 90, 30);

        b1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        b1.setLabel("Save");
        b1.setName(""); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        add(b1);
        b1.setBounds(10, 330, 90, 27);

        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t3KeyPressed(evt);
            }
        });
        add(t3);
        t3.setBounds(120, 110, 210, 20);

        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
        });
        add(t4);
        t4.setBounds(120, 140, 210, 20);

        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
        });
        add(t5);
        t5.setBounds(120, 170, 210, 20);

        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t6KeyPressed(evt);
            }
        });
        add(t6);
        t6.setBounds(120, 200, 210, 20);

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });
        add(t1);
        t1.setBounds(120, 50, 210, 20);

        subj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjActionPerformed(evt);
            }
        });
        add(subj);
        subj.setBounds(120, 290, 150, 20);

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        t8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t8KeyPressed(evt);
            }
        });
        add(t8);
        t8.setBounds(120, 260, 50, 20);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        add(t2);
        t2.setBounds(120, 80, 60, 20);

        label20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label20.setName("l1"); // NOI18N
        label20.setText("Name:");
        add(label20);
        label20.setBounds(30, 50, 50, 23);

        label21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label21.setName("l1"); // NOI18N
        label21.setText("Experience");
        add(label21);
        label21.setBounds(20, 260, 90, 23);

        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t7KeyPressed(evt);
            }
        });
        add(t7);
        t7.setBounds(120, 230, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try{
         System.out.println(a3+"-"+a2+"-"+a1);  
        stmt=con.prepareStatement("insert into teacher(DOJ,name,age,Fathername,Phoneno,EmailId,Address,Expirence,Subject) values(?,?,?,?,?,?,?,?,?)");
        stmt.setString(1,a3+"-"+a2+"-"+a1);
        stmt.setString(2,t1.getText());
        stmt.setString(3,t2.getText());
        stmt.setString(4,t3.getText());
        stmt.setString(5,t4.getText());
        stmt.setString(6,t5.getText());
        stmt.setString(7,t6.getText()+","+t7.getText());
        stmt.setString(8,t8.getText());
        stmt.setString(9,subj.getText());
        stmt.executeUpdate();
        t1.setText(" ");
        t2.setText(" ");
        t3.setText(" ");
        t4.setText(" ");
        t5.setText(" ");
        t6.setText(" ");
        t7.setText(" ");
        t8.setText(" ");
        subj.setText(" ");
        JOptionPane.showMessageDialog(this,"Information Saved");
        }catch(Exception ee){System.out.println("error:"+ee);}
    }//GEN-LAST:event_b1ActionPerformed

    private void subjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t2.requestFocus();}
    }//GEN-LAST:event_t1KeyPressed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        // TODO add your handling code here:
         
        int a=evt.getKeyCode();
        if(a==10){t3.requestFocus();}
    }//GEN-LAST:event_t2KeyPressed

    private void t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t4.requestFocus();}
    }//GEN-LAST:event_t3KeyPressed

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t5.requestFocus();}
    }//GEN-LAST:event_t4KeyPressed

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
        // TODO add your handling code here:
        String s1=t5.getText();
        int a=evt.getKeyCode();
        if(a==10)
        {if(s1.endsWith(".com")||s1.endsWith(".in")){  }else{ JOptionPane.showMessageDialog(this,"invalid Email Id"); t5.setText(" "); }}
        //int a=evt.getKeyCode();
        if(a==10){t6.requestFocus();}
    }//GEN-LAST:event_t5KeyPressed

    private void t6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t7.requestFocus();}
    }//GEN-LAST:event_t6KeyPressed

    private void t7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){t8.requestFocus();}
    }//GEN-LAST:event_t7KeyPressed

    private void t8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t8KeyPressed
        // TODO add your handling code here:
         int a=evt.getKeyCode();
        if(a==10){subj.requestFocus();}
    }//GEN-LAST:event_t8KeyPressed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherrecruited().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button b1;
    private java.awt.Button b2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label17;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField subj;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    private java.awt.TextField t3;
    private java.awt.TextField t4;
    private java.awt.TextField t5;
    private java.awt.TextField t6;
    private java.awt.TextField t7;
    private java.awt.TextField t8;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
